version: '3.8'

services:
  #strapi setup
  strapi:
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: mongo
      DATABASE_NAME: strapi
      DATABASE_HOST: mongo
      DATABASE_PORT: 27017
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    volumes:
      - ./app:/srv/app
    ports:
      - '1337:1337'
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: strapi
      MONGO_INITDB_ROOT_USERNAME: strapi
      MONGO_INITDB_ROOT_PASSWORD: strapi
    volumes:
      - ./data:/data/db

  # Node API Service
  nextapp:
    image: nazmulhawlader/muscled:v8
    ports:
      - 5000:5000
    container_name: next-nest-app
    environment:
      NODE_ENV: production
      PORT: 5000
    depends_on:
      - strapi
    networks:
      - muscled-new-network

networks:
  muscled-new-network:
    driver: bridge
